---
- name: Example Playbook
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: netr0m.infra  # noqa syntax-check[specific]
      src: git+https://github.com/netr0m/netr0m.infra.git
...
