---
- name: Ensure authentik directory is present
  ansible.builtin.file:
    path: "{{ infra_authentik_directory_path }}"
    state: directory
    owner: "{{ infra_authentik_directory_owner }}"
    group: "{{ infra_authentik_directory_group }}"
    mode: "{{ infra_authentik_directory_mode }}"

- name: Ensure authentik subdirectories are present
  ansible.builtin.file:
    path: "{{ infra_authentik_directory_path }}/{{ item }}"
    state: directory
    owner: "{{ infra_authentik_subdirectory_owner }}"
    group: "{{ infra_authentik_subdirectory_group }}"
    mode: "{{ infra_authentik_subdirectory_mode }}"
  with_items: "{{ infra_authentik_subdirectories }}"

- name: Manage service files
  block:
    - name: Write authentik DB password secret to file
      ansible.builtin.template:
        src: secret.j2
        dest: "{{ infra_authentik_db_password_file_path }}"
        owner: "{{ infra_authentik_directory_owner }}"
        group: "{{ infra_authentik_directory_group }}"
        mode: "{{ infra_authentik_secret_file_mode }}"
        backup: true
      vars:
        _secret: "{{ infra_authentik_db_password }}"
      register: authentik_db_password_file_output

    - name: Write authentik environment variables to file
      ansible.builtin.template:
        src: template.env.j2
        dest: "{{ infra_authentik_env_file_path }}"
        owner: "{{ infra_authentik_directory_owner }}"
        group: "{{ infra_authentik_directory_group }}"
        mode: "{{ infra_authentik_env_file_mode }}"
        backup: true
      vars:
        _env_vars: "{{ infra_authentik_env_vars_shared | combine(infra_authentik_server_env_vars) | combine(infra_authentik_settings) }}"
      register: authentik_env_file_output

    - name: Write authentik DB environment variables to file
      ansible.builtin.template:
        src: template.env.j2
        dest: "{{ infra_authentik_db_env_file_path }}"
        owner: "{{ infra_authentik_directory_owner }}"
        group: "{{ infra_authentik_directory_group }}"
        mode: "{{ infra_authentik_env_file_mode }}"
        backup: true
      vars:
        _env_vars: "{{ infra_authentik_env_vars_shared | combine(infra_authentik_db_env_vars) }}"
      register: authentik_db_env_file_output

    - name: Copy compose services file into place
      ansible.builtin.template:
        src: compose/authentik.yml.j2
        dest: "{{ infra_authentik_compose_path }}"
        owner: "{{ infra_authentik_directory_owner }}"
        group: "{{ infra_authentik_directory_group }}"
        mode: "{{ infra_authentik_file_mode }}"
        backup: true
        validate: docker compose -f %s config -q
      register: compose_file_output

- name: Take down services due to changed compose file
  community.docker.docker_compose_v2:
    project_src: "{{ infra_authentik_directory_path }}"
    files: "{{ compose_file_output.backup_file }}"
    state: absent
    remove_orphans: true
  when: compose_file_output.backup_file is defined

- name: Pull container images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ infra_authentik_container_image }}"
    - "{{ infra_authentik_redis_container_image }}"
    - "{{ infra_authentik_db_container_image }}"

- name: Deploy authentik services
  community.docker.docker_compose_v2:
    project_src: "{{ infra_authentik_directory_path }}"
    state: "{{ 'present' if infra_use_authentik else 'absent' }}"
    wait: true
    wait_timeout: "{{ infra_compose_wait_timeout }}"
  register: deploy_authentik_services_output

- name: Add docker-volume-backup entries
  when: infra_backup_enabled
  ansible.builtin.set_fact:
    infra_docker_volume_backup_services_authentik:
      - service: "{{ infra_authentik_service_name }}"
        volumes:
          - "{{ infra_authentik_db_volume_name_data }}"
        stop:
          - "{{ infra_authentik_service_name }}"
...
