---
- name: Ensure uptimekuma directory is present
  ansible.builtin.file:
    path: "{{ infra_uptimekuma_directory_path }}"
    state: directory
    owner: "{{ infra_uptimekuma_directory_owner }}"
    group: "{{ infra_uptimekuma_directory_group }}"
    mode: "{{ infra_uptimekuma_directory_mode }}"

- name: Manage service files
  block:
    - name: Write uptimekuma environment variables to file
      ansible.builtin.template:
        src: template.env.j2
        dest: "{{ infra_uptimekuma_env_file_path }}"
        owner: "{{ infra_uptimekuma_directory_owner }}"
        group: "{{ infra_uptimekuma_directory_group }}"
        mode: "{{ infra_uptimekuma_env_file_mode }}"
        backup: true
      vars:
        _env_vars: "{{ infra_uptimekuma_settings | combine(infra_uptimekuma_env_vars) }}"
      register: uptimekuma_env_file_output

    - name: Copy compose services file into place
      ansible.builtin.template:
        src: compose/uptimekuma.yml.j2
        dest: "{{ infra_uptimekuma_compose_path }}"
        owner: "{{ infra_uptimekuma_directory_owner }}"
        group: "{{ infra_uptimekuma_directory_group }}"
        mode: "{{ infra_uptimekuma_file_mode }}"
        backup: true
        validate: docker compose -f %s config -q
      register: compose_file_output

- name: Take down services due to changed compose file
  community.docker.docker_compose_v2:
    project_src: "{{ infra_uptimekuma_directory_path }}"
    files: "{{ compose_file_output.backup_file }}"
    state: absent
    remove_orphans: true
  when: compose_file_output.backup_file is defined

- name: Pull container images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ infra_uptimekuma_container_image }}"

- name: Deploy uptimekuma services
  community.docker.docker_compose_v2:
    project_src: "{{ infra_uptimekuma_directory_path }}"
    state: "{{ 'present' if infra_use_uptimekuma else 'absent' }}"
    wait: true
    wait_timeout: "{{ infra_compose_wait_timeout }}"
  register: deploy_uptimekuma_services_output

- name: Add docker-volume-backup entries
  when: infra_backup_enabled
  ansible.builtin.set_fact:
    infra_docker_volume_backup_services_uptimekuma:
      - service: "{{ infra_uptimekuma_service_name }}"
        volumes:
          - "{{ infra_uptimekuma_volume_name_data }}"
        stop:
          - "{{ infra_uptimekuma_service_name }}"
...
