---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - 'main.yml'
      paths:
        - 'vars'

# Gather user facts
- name: Include 'user_facts' tasks
  ansible.builtin.import_tasks: user_facts.yml

# Manage directories
- name: Include 'directories' tasks
  ansible.builtin.import_tasks: directories.yml
  when: infra_manage_directories

# Manage pihole deployment
- name: Include 'pihole' tasks
  ansible.builtin.import_tasks: deploy_pihole.yml
  when: infra_use_pihole

# Manage unifi deployment
- name: Include 'unifi' tasks
  ansible.builtin.import_tasks: deploy_unifi.yml
  when: infra_use_unifi

# Manage wireguard deployment
- name: Include 'wireguard' tasks
  ansible.builtin.import_tasks: deploy_wireguard.yml
  when: infra_use_wireguard

# Manage vaultwarden deployment
- name: Include 'vaultwarden' tasks
  ansible.builtin.import_tasks: deploy_vaultwarden.yml
  when: infra_use_vaultwarden
...
