---
# Gather user facts
- name: Include 'user_facts' tasks
  ansible.builtin.import_tasks: user_facts.yml

# Manage directories
- name: Include 'directories' tasks
  ansible.builtin.import_tasks: directories.yml
  when: infra_manage_directories

# Manage pihole deployment
- name: Include 'pihole' tasks
  ansible.builtin.import_tasks: deploy_pihole.yml
  when: infra_use_pihole

# Manage graylog deployment
- name: Include 'graylog' tasks
  ansible.builtin.import_tasks: deploy_graylog.yml
  when: infra_use_graylog

# Manage unifi deployment
- name: Include 'unifi' tasks
  ansible.builtin.import_tasks: deploy_unifi.yml
  when: infra_use_unifi

# Manage wireguard deployment
- name: Include 'wireguard' tasks
  ansible.builtin.import_tasks: deploy_wireguard.yml
  when: infra_use_wireguard

# Manage vaultwarden deployment
- name: Include 'vaultwarden' tasks
  ansible.builtin.import_tasks: deploy_vaultwarden.yml
  when: infra_use_vaultwarden

# Manage authentik deployment
- name: Include 'authentik' tasks
  ansible.builtin.import_tasks: deploy_authentik.yml
  when: infra_use_authentik

# Manage godns deployment
- name: Include 'godns' tasks
  ansible.builtin.import_tasks: deploy_godns.yml
  when: infra_use_godns

# Manage uptimekuma deployment
- name: Include 'uptimekuma' tasks
  ansible.builtin.import_tasks: deploy_uptimekuma.yml
  when: infra_use_uptimekuma

# Manage wazuh deployment
- name: Include 'wazuh' tasks
  ansible.builtin.import_tasks: deploy_wazuh.yml
  when: infra_use_wazuh

# Manage docker-volume-backup deployment
- name: Include 'deploy_docker-volume-backup' from 'netr0m.svc'
  ansible.builtin.include_role:
    name: netr0m.svc
    tasks_from: 'deploy_docker-volume-backup'
    apply:
      tags:
        - 'always'
  vars:
    svc_docker_volume_backup_directory_path: "{{ infra_directory_path }}/docker-volume-backup"
    svc_docker_volume_backup_directory_owner: "{{ infra_directory_owner }}"
    svc_docker_volume_backup_directory_group: "{{ infra_directory_group }}"
    svc_docker_volume_backup_directory_mode: "{{ infra_directory_mode }}"
    svc_docker_volume_backup_file_mode: "{{ infra_file_mode }}"
    svc_docker_volume_backup_service_name: "docker-volume-backup-{{ infra_role_name }}"
    svc_docker_volume_backup_restart_policy: "{{ infra_restart_policy }}"
    __svc_docker_volume_backup_service_var_prefix: "infra_docker_volume_backup_services"
  when: infra_backup_enabled
...
