---
# Gather user facts
- name: Include 'user_facts' tasks
  ansible.builtin.import_tasks: user_facts.yml

# Manage directories
- name: Include 'directories' tasks
  ansible.builtin.import_tasks: directories.yml
  when: infra_manage_directories

# Manage graylog deployment
- name: Include 'graylog' tasks
  ansible.builtin.import_tasks: deploy_graylog.yml
  when: infra_use_graylog

# Manage pihole deployment
- name: Include 'pihole' tasks
  ansible.builtin.import_tasks: deploy_pihole.yml
  when: infra_use_pihole

# Manage unifi deployment
- name: Include 'unifi' tasks
  ansible.builtin.import_tasks: deploy_unifi.yml
  when: infra_use_unifi

# Manage wireguard deployment
- name: Include 'wireguard' tasks
  ansible.builtin.import_tasks: deploy_wireguard.yml
  when: infra_use_wireguard

# Manage vaultwarden deployment
- name: Include 'vaultwarden' tasks
  ansible.builtin.import_tasks: deploy_vaultwarden.yml
  when: infra_use_vaultwarden

# Manage authentik deployment
- name: Include 'authentik' tasks
  ansible.builtin.import_tasks: deploy_authentik.yml
  when: infra_use_authentik

# Manage godns deployment
- name: Include 'godns' tasks
  ansible.builtin.import_tasks: deploy_godns.yml
  when: infra_use_godns

# Manage uptimekuma deployment
- name: Include 'uptimekuma' tasks
  ansible.builtin.import_tasks: deploy_uptimekuma.yml
  when: infra_use_uptimekuma
...
