---
- name: Create password hash for user '{{ item.user }}'
  block:
    - name: Run hash.sh
      community.docker.docker_container:
        image: "{{ infra_wazuh_indexer_container_image }}"
        name: "{{ infra_wazuh_indexer_service_name }}-pwhash"
        command: bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh -p {{ item.password }}
        interactive: true
        detach: false
      register: docker_hash_password_result

    - name: Set temporary password hash variable
      ansible.builtin.set_fact:
        __extracted_pw_hash: "{{ docker_hash_password_result.container.Output | trim | split('\n') | last }}"
      when: docker_hash_password_result.container.Output

    - name: Set password hash fact for '{{ infra_wazuh_indexer_admin_user }}'
      when: item.user == infra_wazuh_indexer_admin_user
      ansible.builtin.set_fact:
        __infra_wazuh_indexer_admin_password_hash: "{{ __extracted_pw_hash }}"
      failed_when:
        - __extracted_pw_hash is not regex('^\$.*')

    - name: Set password hash fact for '{{ infra_wazuh_indexer_dashboard_user }}'
      when: item.user == infra_wazuh_indexer_dashboard_user
      ansible.builtin.set_fact:
        __infra_wazuh_indexer_dashboard_password_hash: "{{ __extracted_pw_hash }}"
      failed_when:
        - __extracted_pw_hash is not regex('^\$.*')

- name: Cleanup password hashing container
  community.docker.docker_container:
    image: "{{ infra_wazuh_indexer_container_image }}"
    name: "{{ infra_wazuh_indexer_service_name }}-pwhash"
    state: absent
...
