---
name: 'CI'
on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    working-directory: 'netr0m.infra'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      dirname: 'netr0m.infra'
  molecule:
    uses: ./.github/workflows/molecule.yml
    with:
      dirname: 'netr0m.infra'
...
