---
name: 'Molecule'
on:
  workflow_dispatch:
    inputs:
      dirname:
        description: 'Name of the directory to checkout to'
        default: 'netr0m.infra'
        required: false
        type: string
  workflow_call:
    inputs:
      dirname:
        description: 'Name of the directory to checkout to'
        default: 'netr0m.infra'
        required: false
        type: string
    secrets:
      ANSIBLE_ROLE_SVC_SSH_KEY:
        required: true

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  molecule:
    name: 'Run molecule'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        distro:
          - debian13
          - ubuntu2404
    steps:
      - name: Delete unnecessary tools folder (disk space constraint)
        run: rm -rf /opt/hostedtoolcache

      - name: 'Check out the codebase'
        uses: 'actions/checkout@master'
        with:
          path: ${{ inputs.dirname }}

      - name: 'Check out the dependency codebase'
        uses: actions/checkout@v3
        with:
          repository: netr0m/ansible-role-svc
          path: netr0m.svc
          ref: main
          ssh-key: ${{ secrets.ANSIBLE_ROLE_SVC_SSH_KEY }}

      - name: 'Set up Python 3.10'
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: 'Run molecule tests'
        run: |
          cd ${{ inputs.dirname }}
          molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
...
